name: Scully Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Blog
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: '10.x'
      - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # - name: Scully Publish
      - uses: cmgriffing/scully-gh-pages-action@v8
        with:
          access-token: 27edf2d78714f1c6c80865b97188cf856a7d3cee
      # - name: Build 
      - run: |
          npm install
          npm run-script build
          npm run-script scully
      - name: Deploy
      - uses: JamesIves/github-pages-deploy-action@releases/v3 
        with:
          access-token: 27edf2d78714f1c6c80865b97188cf856a7d3cee
          BRANCH: master
          FOLDER: dist/blog
